POST http://localhost:4000/user/register
Content-Type: application/json

{
    "email":"govind@gmail.om",
    "password":"krishna",
    "name":"radha",
    "mobile":"0210082222",
    "location":"female",
    "gender":"female",
    "isSeller":true
}

###
GET http://localhost:4000/products

###
GET http://localhost:4000/product/63c7c952078701e7641f8ab4

###
GET http://localhost:4000/products?category=All&price=HighToLow&quality=1&search=""&saleType=general

###
GET http://localhost:4000/products?category=All&price=LowToHigh&quality=4&search=""&saleType=general

###
POST https://dibuybe.onrender.com/user/verify
Content-Type: application/json

{
    "email":"bsjdfk@gmail.om"
}

###
GET http://localhost:4000/users/srinusri76585@gmail.com


###
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJwcmFrYXNoZHVtcGExNDNAZ21haWwuY29tIiwiaWF0IjoxNjc0NzM2Mzg5fQ.pIFXtOcnlP7WEpqCCifG6aYnZZrmCo1gKxEgr0ZtDxI
###
POST http://localhost:4000/user/cart/update
Content-Type: application/jsoneyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJwcmFrYXNoZHVtcGExNDNAZ21haWwuY29tIiwiaWF0IjoxNjc0NzM2Mzg5fQ.pIFXtOcnlP7WEpqCCifG6aYnZZrmCo1gKxEgr0ZtDxI
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

{
    "productId":"63c7c952078701e7641f8ab6",
    "quantity": 100
}

###
GET http://localhost:4000/user/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY



###
POST http://localhost:4000/user/cart/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
    "productId":"63c7c952078701e764hf8ab5"
}

###
POST http://localhost:4000/user/cart/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
    "ordered":true,
    "cartValue":400
}

###
GET http://localhost:4000/user/cart/orders/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

###
POST http://localhost:4000/seller/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
    "accountNumber":1234512345,
    "IFSC":"akajsdfk",
    "accountHolderName":"Srinu meesala"
}

###
GET http://localhost:4000/seller/details
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
POST http://localhost:4000/products/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
      "category": "others",
      "title": "aaaa",
      "quantity": "100",
      "quality": "4.6",
      "price": 1000,
      "description": "Hare Krishna mahamantra is the best one in the world for salvation.",
      "imageUrl":"",
      "saleType":"government"
}

###
GET http://localhost:4000/seller/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
GET http://localhost:4000/user/qr
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
GET http://localhost:4000/user/getemail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
POST http://localhost:4000/user/update?newpassword=&profilepic=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY


###
GET http://localhost:4000/product/63c7c952078701e7641f8ab4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
GET http://localhost:4000/products/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY


###
GET http://localhost:4000/products/products-for-govt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY


###
POST http://localhost:4000/admin/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
      "adminId":"krishna",
      "password":"krishna"
}

###
GET http://localhost:4000/fair-price?search=oats&category=grains
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
GET http://localhost:4000/fair-price/getproducts?category=
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY

###
POST http://localhost:4000/fair-price/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
    "category":"grains",
    "product":"Wheat",
    "dealerPrice":2777,
    "mrp":3777
}



###
POST http://localhost:4000/admin/token-authentication
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRW1haWwiOiJzcmludXNyaTc2NTg1QGdtYWlsLmNvbSIsImlhdCI6MTY3NDcwODgzMX0.QNkp8Y4jhoKIezwAm8Nc4RYtHYeTX7AbgifIRLfCvpY
Content-Type: application/json

{
    "key":"eyJhbGciOiJUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjoic3JpbnVzcmk3NjU4NUBnbWFpbC5jb20iLCJpYXQiOjE2NzczOTMzMzh9.0QyReDCpYRy0ql7neSx4lVPRyGgBIPUwQ7yETHBBHGY"
}